version: '3.4'

services:
  database:
    container_name: fincontrol__db
    image: bitnami/postgresql
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: admin
      POSTGRES_DB: fincontrol__db
    ports:
      - 5432:5432
    volumes:
      - pg:/var/lib/mysql
    networks:
      - fincontrol
      
  redis:
    image: redis:alpine
    container_name: fincontrol__redis
    ports:
      - "6379:6379"
    networks:
      - fincontrol

volumes:
  pg:


networks:
  fincontrol:
    driver: bridge
